### ISSUE TITLE
Using variables

### ISSUE THREAD

**Issue by bkniffler** [babyfish-ct/graphql-ts-client#3]
Variables seem to not be currently supported, even though they are a really important part of what makes GQL. A similar library has this syntax, maybe its helpful: https://github.com/graphql-editor/graphql-zeus#variables

**Comment by babyfish-ct** [comment]
Variables have two sources

1. Mostly case, parameters from query or mutation. This case is fully supported because it is too important. 

At the end of generated file [https://github.com/babyfish-ct/graphql-ts-client/blob/master/example/client/apollo-demo/src/__generated/Queries.ts](https://github.com/babyfish-ct/graphql-ts-client/blob/master/example/client/apollo-demo/src/__generated/Queries.ts), you can see
```
const GQL_PARAMS: {[key: string]: string} = {
	"findDepartmentsLikeName": "($name: String)", 
	"findEmployees": "($mockedErrorProbability: Int, $supervisorId: String, $departmentId: String, $name: String)"
};

const GQL_ARGS: {[key: string]: string} = {
	"findDepartmentsLikeName": "(name: $name)", 
	"findEmployees": "(mockedErrorProbability: $mockedErrorProbability, supervisorId: $supervisorId, departmentId: $departmentId, name: $name)"
};
```

so can can uses variables like this
```
const { loading, data, error } = useTypedQuery(
    "findDepartmentsLikeName",
    department$$,
    {
        variables: { name: 'abc' }
    }
);

const { loading, data, error } = useTypedQuery(
    "findEmployees",
    {
        variables: { 
            input: {
                name: 'abc',
                supervisorId: undefined
                departmentId: underined
            }
        }
    }
);
```

You can run the [full apollo-demo](https://github.com/babyfish-ct/graphql-ts-client/blob/master/example/client/apollo-demo), it's works.

2. Object field can also support parameters. But as far as this situation is concerned, there is no decision to choose which method to use to implement the strongly typed code style. Currently it can be provided using literals, for example (if Department.employees supports a parameter named type)

```
const { loading, data, error } = useTypedQuery(
    "findDepartmentsLikeName",
    department$$
    .employees(
        employee$$,
        { type: "REGULAR" } // Parameters of object field, not from query or mutation
    )
);
```

In the next version, "2" will be supported as perfected as "1"
